version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend/:/var/www/html
    ports:
      - "8080:${FRONTEND_PORT}"
    networks:
      - projectNetwork

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - ./.env
    volumes:
      - ./backend/src/:/app/src/
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - projectNetwork

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - ./db/init_scripts/:/docker-entrypoint-initdb.d
    #      - ./db/database-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - projectNetwork

networks:
  projectNetwork:
    driver: bridge
